---
- name: Install and start web server
  hosts: ubuntu_hosts:redhat_hosts
  become: true

  tasks:
    - name: Install Apache web server
      apt:
        name: apache2
        state: latest
      when: " ansible_os_family == 'Debian'"

    - name: Install httpd web server
      yum:
        name: httpd
        state: latest
      when: " ansible_os_family == 'RedHat'"

    - name: Start web server
      service:
        name: apache2
        state: started
      when: " ansible_os_family == 'Debian'"

    - name: Start web server
      service:
        name: httpd
        state: started
      when: " ansible_os_family == 'RedHat'"
